<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Grapevine</PackageId>
    <Description>Fast, unopinionated, embeddable, minimalist REST framework for .NET built on HttpClient</Description>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Grapevine.Tests, PublicKey=$(GrapevinePublicKey)" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Grapevine.Abstractions\Grapevine.Abstractions.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>