<Project>

  <PropertyGroup Label="Common">
    <TargetFrameworks>netstandard2.0;netstandard2.1;net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CheckEolTargetFramework>false</CheckEolTargetFramework>
    <PackageIcon>grapevine.png</PackageIcon>
  </PropertyGroup>

  <PropertyGroup Label="StrongNaming">
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(MSBuildThisFileDirectory)Grapevine.snk</AssemblyOriginatorKeyFile>
    <PublicSign Condition="'$(OS)' != 'Windows_NT'">true</PublicSign>
    <GrapevinePublicKey>0024000004800000940000000602000000240000525341310004000001000100792488c755d7dd913e0d2ded441c94583d64e3266f598ba54221e04c135a2b85eae032defe2279f1ae917a378d8c51f21f0d8f06c051a66a110e07b8bb3b48bdf0aeb008f23d570e661948d0ffeeb0c5d6a9f31d0398dcfbe92c14aa35fd382abc9531e80f673962075a460658297ab9e17f1c36a0ad74f9c5ab8fe2104409ec</GrapevinePublicKey>
  </PropertyGroup>

  <PropertyGroup Label="Repository">
    <Authors>Scott Offen</Authors>
    <Copyright>© 2014 - $([System.DateTime]::UtcNow.Year) Scott Offen</Copyright>
    <RepositoryUrl>https://github.com/scottoffen/grapevine</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://scottoffen.github.io/grapevine/</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>

  <PropertyGroup Label="Packaging">
    <PackageLicenseExpression>MIT OR Apache-2.0</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>rest;http;api;web;router;client;server;express;json;xml;embedded</PackageTags>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <!-- <EnablePackageValidation>true</EnablePackageValidation> -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup Label="GitVersioning">
    <GitVersionBaseDirectory>$(MSBuildThisFileDirectory)</GitVersionBaseDirectory>
  </PropertyGroup>

  <ItemGroup Label="AssemblyAttributes">
    <AssemblyAttribute Include="System.Runtime.InteropServices.ComVisibleAttribute">
      <_Parameter1>false</_Parameter1>
      <_Parameter1_IsLiteral>true</_Parameter1_IsLiteral>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup Label="BuildPackages">
    <PackageReference Include="Nerdbank.GitVersioning" Version="3.9.50" Condition="!Exists('packages.config')">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup Label="PackageFiles">
    <None Include="..\..\grapevine.png" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>